version: '3.5'

services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: iogt
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: iogt.settings.production
      COMMIT_HASH: asdfghjkl
      RAPIDPRO_BOT_USER_ID: 1
      RAPIDPRO_BOT_USER_USERNAME: rapidpro
      RAPIDPRO_BOT_USER_PASSWORD: 1234
      WAGTAILTRANSFER_SECRET_KEY: wagtailtransfer-secret-key
      WAGTAILTRANSFER_SOURCE_NAME: iogt_global
      WAGTAILTRANSFER_SOURCE_BASE_URL: https://example.com/wagtail-transfer/
      WAGTAILTRANSFER_SOURCE_SECRET_KEY: wagtailtransfer-source-secret-key
      STATIC_URL: '//localhost:9000/static/'
      MEDIA_URL: '//localhost:9000/media/'
      BASE_URL: 'http://localhost:8000'
      SECRET_KEY: 'django_secret_key'
      DB_SSL_MODE: allow
      ROOT_LOG_LEVEL: DEBUG
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - db
      - static

  # static:
  #   image: caddy:alpine
  #   restart: unless-stopped
  #   ports:
  #     - '9000:80'
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - ./static:/usr/share/caddy/static:ro
  #     - ./media/images:/usr/share/caddy/media/images:ro
  #     - ./media/media:/usr/share/caddy/media/media:ro
  #     - ./media/svg-to-png-maps:/usr/share/caddy/media/svg-to-png-maps:ro
  #     - /data
  #     - /config

  static:
    image: nginx
    ports:
      - '9000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html/static:ro
      - ./media/images:/usr/share/nginx/html/media/images:ro
      - ./media/media:/usr/share/nginx/html/media/media:ro
      - ./media/svg-to-png-maps:/usr/share/nginx/html/media/svg-to-png-maps:ro

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.12.1'
    environment:
      - discovery.type=single-node
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: iogt
    volumes:
      - /var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  # legacy-db:
  #   image: postgres:alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: iogt
  #   volumes:
  #     - /var/lib/postgresql/data
  #     - ./legacy-initdb.d:/docker-entrypoint-initdb.d
  #   ports:
  #     - 54321:5432

volumes:
  es-data01:
